<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV3Z4g18\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV3Z4g18/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerV3Z4g18.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerV3Z4g18\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerV3Z4g18\App_KernelProdContainer([
    'container.build_hash' => 'V3Z4g18',
    'container.build_id' => '85ef52b7',
    'container.build_time' => 1687168993,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV3Z4g18');
