<?php

namespace ContainerV3Z4g18;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AQiqhzWService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.aQiqhzW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aQiqhzW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repoCategorie' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'repoProduits' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
        ], [
            'repoCategorie' => 'App\\Repository\\CategorieRepository',
            'repoProduits' => 'App\\Repository\\ProduitsRepository',
        ]);
    }
}
