<?php

namespace ContainerV3Z4g18;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginAuthentificatorAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\LoginAuthentificatorAuthenticator' shared autowired service.
     *
     * @return \App\Security\LoginAuthentificatorAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\LoginAuthentificatorAuthenticator'] = new \App\Security\LoginAuthentificatorAuthenticator(($container->services['router'] ?? $container->getRouterService()));
    }
}
