<?php

namespace ContainerV3Z4g18;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMentionsLegalesControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MentionsLegalesController' shared autowired service.
     *
     * @return \App\Controller\MentionsLegalesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MentionsLegalesController'] = $instance = new \App\Controller\MentionsLegalesController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\MentionsLegalesController', $container));

        return $instance;
    }
}
