<?php

namespace ContainerV3Z4g18;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ProfilType' shared autowired service.
     *
     * @return \App\Form\ProfilType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ProfilType'] = new \App\Form\ProfilType();
    }
}
