<?php

namespace ContainerV3Z4g18;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduits2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Gt8.nf1.App\Entity\Produits' shared service.
     *
     * @return \App\Entity\Produits
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Gt8.nf1": it references class "App\\Entity\\Produits" but no such service exists.');
    }
}
