<?php

namespace ContainerNxoU3gu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BYyXXA4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BYyXXA4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BYyXXA4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'produits' => ['privates', '.errored..service_locator.BYyXXA4.App\\Entity\\Produits', NULL, 'Cannot autowire service ".service_locator.BYyXXA4": it references class "App\\Entity\\Produits" but no such service exists.'],
        ], [
            'produits' => 'App\\Entity\\Produits',
        ]);
    }
}
