<?php

namespace ContainerZELoBty;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OLoBuJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OLo_BuJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OLo_BuJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repoCategorie' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'repoProduits' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
        ], [
            'manager' => '?',
            'repoCategorie' => 'App\\Repository\\CategorieRepository',
            'repoProduits' => 'App\\Repository\\ProduitsRepository',
        ]);
    }
}
