<?php

namespace ContainerZELoBty;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduits3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hoy52hl.App\Entity\Produits' shared service.
     *
     * @return \App\Entity\Produits
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hoy52hl": it references class "App\\Entity\\Produits" but no such service exists.');
    }
}
