<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxoU3gu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxoU3gu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNxoU3gu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNxoU3gu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNxoU3gu\App_KernelDevDebugContainer([
    'container.build_hash' => 'NxoU3gu',
    'container.build_id' => 'e55f5a7d',
    'container.build_time' => 1690845686,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxoU3gu');
